services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      django_app:
        condition: service_healthy

  django_app:
    build:
      context: .
    expose:
      - "8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys;\ntry:\n  r=urllib.request.urlopen('http://localhost:8000/admin',timeout=5);\n  sys.exit(0 if r.getcode() < 500 else 1)\nexcept Exception:\n  sys.exit(1)\n\" "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
